<?php
// DO NOT CHANGE THIS FILE! It is automatically generated by Tx_Extbase_Utility_Extension::createAutoloadRegistryForExtension.
// This file was generated on 2009-08-21 22:34

$extensionClassesPath = t3lib_extMgm::extPath('zefueg_dealer') . 'Classes/';
return array(
	'tx_zefuegdealer_controller_regioncontroller' => $extensionClassesPath . 'Controller/RegionController.php',
	'tx_zefuegdealer_domain_repository_dealerrepository' => $extensionClassesPath . 'Domain/Repository/DealerRepository.php',
	'tx_zefuegdealer_domain_repository_regionrepository' => $extensionClassesPath . 'Domain/Repository/RegionRepository.php',
	'tx_zefuegdealer_domain_model_dealer' => $extensionClassesPath . 'Domain/Model/Dealer.php',
	'tx_zefuegdealer_domain_model_region' => $extensionClassesPath . 'Domain/Model/Region.php',
);
?>